# Generated by Django 3.1.6 on 2021-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_auto_20210330_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintitle',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
