# Generated by Django 3.1.6 on 2021-03-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_auto_20210331_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintitle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='author',
        ),
    ]
