# Generated by Django 3.1.6 on 2021-03-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_auto_20210331_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintitle',
            old_name='user',
            new_name='author',
        ),
    ]
