# Generated by Django 3.1.6 on 2021-03-31 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_auto_20210331_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintitle',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
